# Generated by Django 5.2 on 2025-04-17 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sig', models.IntegerField(unique=True)),
                ('descricao', models.CharField(max_length=100)),
                ('sn', models.CharField(max_length=10, unique=True)),
                ('responsavel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gestores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patrimonios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ni', models.CharField(max_length=10, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('localizacao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Manutentores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.area')),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gestores')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('abertura', models.DateTimeField()),
                ('fechamento', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, 'Iniciada'), (2, 'Pendente'), (3, 'Finalizada'), (4, 'Cancelada')])),
                ('prioridade', models.IntegerField(choices=[(1, 'Alta'), (2, 'Media'), (3, 'Baixa')])),
                ('funcionario', models.CharField(max_length=100)),
                ('snFuncionario', models.CharField(max_length=100)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ambientes')),
                ('manutentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.manutentores')),
                ('patrimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patrimonios')),
            ],
        ),
    ]
