# Generated by Django 5.2 on 2025-04-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambientes',
            name='sn',
            field=models.CharField(max_length=10),
        ),
    ]
