# Generated by Django 5.2 on 2025-05-22 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ambientes_sn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manutentores',
            name='gestor',
        ),
        migrations.RemoveField(
            model_name='manutentores',
            name='area',
        ),
        migrations.RemoveField(
            model_name='ambientes',
            name='sn',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='ambiente',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='snFuncionario',
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.area')),
            ],
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordens_requisitadas', to='api.funcionarios'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='requisitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordens_executadas', to='api.funcionarios'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='manutentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordens_manutentidas', to='api.funcionarios'),
        ),
        migrations.DeleteModel(
            name='Gestores',
        ),
        migrations.DeleteModel(
            name='Manutentores',
        ),
    ]
